-- LEFT ANTI JOIN 
/* ONLY CONSIDERS ALL THE VALUSE IN THE LEFT TABLE
WHICH HAVE COMPLETE MATCH WITH THE DATA IN THE  RIGHT TABLE */

-- GET ALL THE CUSTOMERS WHO HAVEN'T PLACES ANY ORDER

SELECT 
	* 
 FROM CUSTOMERS C
 LEFT JOIN ORDERS O
 ON C.ID = O.CUSTOMER_ID
 WHERE  O.CUSTOMER_ID IS NULL;
 /* GET ALL THE ORDERS WHERE CUSTOMER ID IS NULL*/

  /*SELECT 
  * 
  FROM CUSTOMERS C 
  INNER JOIN ORDERS O
  ON C.ID = O.CUSTOMER_ID; */

SELECT 
	* 
FROM CUSTOMERS C
RIGHT JOIN ORDERS O 
ON C.ID = O.CUSTOMER_ID
WHERE O.CUSTOMER_ID IS NULL;
-- I HAVE 8 CIOLUMNS AND ATLIST ONE CUSTOMER HAS ORDER FROM THE ORDER  TABLE

--USING LEFT JOIN I JUST NEED TO REPLACE THE TABLE POSITION HERE THE LEFT TABLE WIL BECOME THE RIGHT ONE AN THE RIGHT WILL BECOME THE LEFT ONE 

SELECT * FROM
 orders O
 LEFT JOIN CUSTOMERS C 
 ON O.CUSTOMER_ID = C.ID
 WHERE C.ID IS NULL;

 -- FULL ANTIJOIN IN SQL

 -- ONLY THE ROWS THAT DOESN'T HAVE ANY MATCH MATCHES 
 
 --TO USE ANY TYPE O THE ANTY JOIN IT IS NECESSORY TO US WHRE CONDITION

SELECT 
	*
FROM CUSTOMERS C 
FULL JOIN ORDERS O
ON C.ID = O.CUSTOMER_ID
WHERE C.ID IS NULL 
OR O.CUSTOMER_ID IS NULL;
 
DELETE FROM 
 CUSTOMERS  WHERE ID >5;

  SELECT * FROM CUSTOMERS;

  /* GET ALL THE CUSTOMERS ALONG WITH THEIR ORDERS, 
  BUT ONLY FOR CUSTOMERS WHO HAVE PLACED AN ORDER */

SELECT 
	*
FROM CUSTOMERS C
FULL JOIN ORDERS O 
ON C.ID = O.CUSTOMER_ID 
WHERE C.ID IS NOT NULL 
AND O.CUSTOMER_ID IS NOT NULL;

-- Cross join

--Query
select * from 
customers c 
cross  join orders o;
-- Mostly used for combination and testing.


--How to us join type

-- for only matching data type we use the inner join 
-- For all rows we use two methods
-- 1.) Left join To get he data from the left table or th right table by changing the position of the parent table 
--2.) Full join to see the data of the both table that has match and no match .
--ONLY UNMATCHING DATA FROM ONE SIDE WE USE THE LEFT ANTI JOIN TO CHECK THE Data
--For both side we use the full antijoin operation .


