/* GET THE CUSTOMERS ALONG WITH THEIR ORDERS 
INCLUDING ORDERS WITH MATCHING CUSTOMERS 
(USING LEFT JOIN)*/
USE MyDatabase;
-- FOR ALL DATE IN LEFT TABLE 
SELECT 
	* 
FROM 
CUSTOMERS C
LEFT JOIN ORDERS O
ON C.ID =O.customer_id;
--aLL DATA FROM THERIGHT TABLE 

SELECT	* FROM 
ORDERS O
LEFT JOIN CUSTOMERS C
ON O.CUSTOMER_ID =C.ID;
--sIMILAR USING RIGHT JOIN
SELECT 
	* 
FROM 
CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.ID =O.customer_id;

--FULL JOIN
--TO GET ALL DATA ,THE MATCHING AND THE UNMATCHING DATA ALSO
--ORDER DOESNOT MATTER IN THIS  JOIN TYPE
--QUERY
SELECT 
	* 
FROM CUSTOMERS C 
FULL JOIN ORDERS O 
ON C.ID = O.CUSTOMER_ID;

/*TO REMOVE THE NULL VALUES FROM THE NOT MATCHING
VALUES WHICH IS SIMILAR TO THE INNER JOIN*/ 
SELECT 
	C.ID,
	C.FIRST_NAME,
	O.ORDER_ID,
	O.SALES
FROM CUSTOMERS C
FULL JOIN ORDERS O
ON C.ID =O.CUSTOMER_ID
whERE ORDER_ID IS NOT NULL;

